spring.application.name=APIGateway
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

## Route definition
#spring.cloud.gateway.routes[0].id=program-grant
#spring.cloud.gateway.routes[0].uri=lb://program-grant-service
#
## EACH Path predicate MUST BE SEPARATE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/programs/**
#spring.cloud.gateway.routes[0].predicates[1]=Path=/api/applications/**
#
#spring.cloud.config.import-check.enabled=false
#
#eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.routes[0].id=program-grant
spring.cloud.gateway.server.webflux.routes[0].uri=lb://program-grant-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/programs/**
 
# Route for DisbursementController
spring.cloud.gateway.server.webflux.routes[1].id=grant
spring.cloud.gateway.server.webflux.routes[1].uri=lb://program-grant-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/applications/**

spring.cloud.gateway.server.webflux.routes[2].id=citizen
spring.cloud.gateway.server.webflux.routes[2].uri=lb://citizen-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/citizens/**

# Route for Auth Service
spring.cloud.gateway.server.webflux.routes[3].id=auth-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/cultureconnect/**

# Route for HeritageManagement Service
spring.cloud.gateway.server.webflux.routes[4].id=heritage-sites
spring.cloud.gateway.server.webflux.routes[4].uri=lb://heritage-management
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/heritage-sites/**

# Route for HeritageManagement Service
spring.cloud.gateway.server.webflux.routes[5].id=acitvity
spring.cloud.gateway.server.webflux.routes[5].uri=lb://heritage-management
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/activities/**

# Route for event-resource Service
spring.cloud.gateway.server.webflux.routes[6].id=event
spring.cloud.gateway.server.webflux.routes[6].uri=lb://event-resource-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/events/**

# Route for event-resource Service
spring.cloud.gateway.server.webflux.routes[7].id=resource
spring.cloud.gateway.server.webflux.routes[7].uri=lb://event-resource-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/resources/**

# Route for copliance-audit Service
spring.cloud.gateway.server.webflux.routes[8].id=audits
spring.cloud.gateway.server.webflux.routes[8].uri=lb://complianceservice
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/audits/**

# Route for copliance-audit Service
spring.cloud.gateway.server.webflux.routes[9].id=compliance
spring.cloud.gateway.server.webflux.routes[9].uri=lb://complianceservice
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/compliance/**

# Route for notification Service
spring.cloud.gateway.server.webflux.routes[10].id=Notification
spring.cloud.gateway.server.webflux.routes[10].uri=lb://NotificationServices
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/email/**

# Route for notification Service
spring.cloud.gateway.server.webflux.routes[11].id=Notification
spring.cloud.gateway.server.webflux.routes[11].uri=lb://NotificationServices
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/api/notifications/**

# Route for report Service
spring.cloud.gateway.server.webflux.routes[12].id=Report
spring.cloud.gateway.server.webflux.routes[12].uri=lb://ReportAndAnalysisServices
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/api/reports/**

jwt.secret=ECeR4KSw5vhsigaezz97kOAZNb2BKXWKh0XDP1PKWG53mPdBOqtkrtsGxOt3ouxQSko3yQRQ04ADMpk1hlFqEC
# api-gateway application.properties
#spring.security.user.name=disabled
#spring.security.user.password=disabled
spring.security.enabled=false

spring.cloud.config.import-check.enabled=false
eureka.instance.prefer-ip-address=true