spring.application.name=ConfigServer
spring.cloud.config.server.git.uri=https://github.com/HarshadSonule0703/configserver.git
server.port=8711
spring.cloud.config.server.git.skip-ssl-validation=true

spring.cloud.config.server.git.default-label=main
eureka.client.instance.preferIpAddress = true
eureka.instance.hostname=localhost

eureka.client.enabled=false

