spring.application.name=ConfigServer
<<<<<<< HEAD
spring.cloud.config.server.git.uri=https://github.com/HarshadSonule0703/configserver.git
=======
spring.cloud.config.server.git.uri=https://github.com/HarshadSonule0703/configserver
>>>>>>> 9707d2cf5eab1e1f359c08750efd6e80e62c087d
server.port=8711
spring.cloud.config.server.git.skip-ssl-validation=true

spring.cloud.config.server.git.default-label=main
eureka.client.instance.preferIpAddress = true
eureka.instance.hostname=localhost

eureka.client.enabled=false

